"use client"
import { useEffect, useState } from "react"
import { Radio, Video } from "lucide-react"
import { LIVE_SESSIONS } from "@/lib/examvision-data"

export function LiveMonitoring({ onOpen }: { onOpen: (id: string) => void }) {
  const [filter, setFilter] = useState("All"), [scores, setScores] = useState(() => LIVE_SESSIONS.map(x => x.score))
  useEffect(() => { const timer = setInterval(() => setScores(s => s.map(n => Math.max(60, Math.min(100, n + Math.round(Math.random() * 4 - 2))))), 3500); return () => clearInterval(timer) }, [])
  const sessions = LIVE_SESSIONS.filter(x => filter === "All" || (filter === "Flagged only" ? x.state === "flagged" : x.state === "critical"))
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700"><Radio className="size-3 animate-pulse"/>Live now</div><h1 className="text-2xl font-semibold tracking-tight">Live monitoring</h1><p className="mt-1 text-sm text-muted-foreground">A calm, real-time view of active assessment sessions.</p></div><div className="rounded-lg bg-muted p-1">{["All", "Flagged only", "Critical only"].map(x => <button key={x} onClick={() => setFilter(x)} className={`rounded-md px-3 py-1.5 text-sm ${filter === x ? "bg-white font-medium text-blue-700 shadow-sm" : "text-muted-foreground"}`}>{x}</button>)}</div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{sessions.map((s, i) => <button key={s.id} onClick={() => onOpen(s.id)} className="group rounded-2xl border border-border bg-white p-5 text-left shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700">{s.initials}</span><span className={`flex items-center gap-1.5 text-xs font-semibold ${s.state === "critical" ? "text-red-600" : s.state === "flagged" ? "text-amber-600" : "text-emerald-600"}`}><span className={`size-2 rounded-full animate-pulse ${s.state === "critical" ? "bg-red-500" : s.state === "flagged" ? "bg-amber-400" : "bg-emerald-500"}`}/>{s.state === "normal" ? "Normal" : s.state === "critical" ? "Critical" : "Flagged"}</span></div><div className="mt-5"><p className="font-semibold">{s.student}</p><p className="mt-1 text-sm text-muted-foreground">{s.exam}</p></div><div className="mt-5 flex items-end justify-between"><div><p className="text-xs text-muted-foreground">Integrity score</p><p className="mt-1 text-2xl font-bold tracking-tight">{scores[i]}%</p></div><Video className="size-5 text-blue-600 opacity-0 transition group-hover:opacity-100"/></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600 transition-all duration-700" style={{width: `${scores[i]}%`}}/></div></button>)}</div></div>
}
